// GENERATED by `node scripts/gen-nyse-calendar.mjs` — DO NOT EDIT BY HAND.
//
// TRA-4478 — NYSE exchange calendar, one bundle per year. Hand-editing this
// file silently breaks `pnpm check:calendar-coverage`, which re-runs the
// generator and diffs. To change coverage, edit COVERAGE_END_YEAR in the
// generator and re-run it.
//
// `closures` are full-day closures. `earlyCloses` are 13:00 ET sessions.
// Both are ET calendar dates (`YYYY-MM-DD`), ascending within a year.

/** One year of NYSE exchange policy. `[date, name]` pairs. */
export interface NyseCalendarYear {
  year: number;
  closures: ReadonlyArray<readonly [string, string]>;
  earlyCloses: ReadonlyArray<readonly [string, string]>;
}

/**
 * Bumped whenever the generated content changes, so a live host can report
 * WHICH calendar it is running rather than only that it has one.
 */
export const NYSE_CALENDAR_VERSION = 'nyse-2015-2035';

/** First and last ET dates this bundle makes a statement about. */
export const NYSE_CALENDAR_COVERAGE_START = '2015-01-01';
export const NYSE_CALENDAR_COVERAGE_END = '2035-12-31';

export const NYSE_CALENDAR_YEARS: readonly NyseCalendarYear[] = [
  {
    year: 2015,
    closures: [
      ['2015-01-01', 'New Year\'s Day'],
      ['2015-01-19', 'Martin Luther King Jr. Day'],
      ['2015-02-16', 'Washington\'s Birthday'],
      ['2015-04-03', 'Good Friday'],
      ['2015-05-25', 'Memorial Day'],
      ['2015-07-03', 'Independence Day'],
      ['2015-09-07', 'Labor Day'],
      ['2015-11-26', 'Thanksgiving Day'],
      ['2015-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2015-11-27', 'Day after Thanksgiving'],
      ['2015-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2016,
    closures: [
      ['2016-01-01', 'New Year\'s Day'],
      ['2016-01-18', 'Martin Luther King Jr. Day'],
      ['2016-02-15', 'Washington\'s Birthday'],
      ['2016-03-25', 'Good Friday'],
      ['2016-05-30', 'Memorial Day'],
      ['2016-07-04', 'Independence Day'],
      ['2016-09-05', 'Labor Day'],
      ['2016-11-24', 'Thanksgiving Day'],
      ['2016-12-26', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2016-11-25', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2017,
    closures: [
      ['2017-01-02', 'New Year\'s Day'],
      ['2017-01-16', 'Martin Luther King Jr. Day'],
      ['2017-02-20', 'Washington\'s Birthday'],
      ['2017-04-14', 'Good Friday'],
      ['2017-05-29', 'Memorial Day'],
      ['2017-07-04', 'Independence Day'],
      ['2017-09-04', 'Labor Day'],
      ['2017-11-23', 'Thanksgiving Day'],
      ['2017-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2017-07-03', 'Day before Independence Day'],
      ['2017-11-24', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2018,
    closures: [
      ['2018-01-01', 'New Year\'s Day'],
      ['2018-01-15', 'Martin Luther King Jr. Day'],
      ['2018-02-19', 'Washington\'s Birthday'],
      ['2018-03-30', 'Good Friday'],
      ['2018-05-28', 'Memorial Day'],
      ['2018-07-04', 'Independence Day'],
      ['2018-09-03', 'Labor Day'],
      ['2018-11-22', 'Thanksgiving Day'],
      ['2018-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2018-07-03', 'Day before Independence Day'],
      ['2018-11-23', 'Day after Thanksgiving'],
      ['2018-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2019,
    closures: [
      ['2019-01-01', 'New Year\'s Day'],
      ['2019-01-21', 'Martin Luther King Jr. Day'],
      ['2019-02-18', 'Washington\'s Birthday'],
      ['2019-04-19', 'Good Friday'],
      ['2019-05-27', 'Memorial Day'],
      ['2019-07-04', 'Independence Day'],
      ['2019-09-02', 'Labor Day'],
      ['2019-11-28', 'Thanksgiving Day'],
      ['2019-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2019-07-03', 'Day before Independence Day'],
      ['2019-11-29', 'Day after Thanksgiving'],
      ['2019-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2020,
    closures: [
      ['2020-01-01', 'New Year\'s Day'],
      ['2020-01-20', 'Martin Luther King Jr. Day'],
      ['2020-02-17', 'Washington\'s Birthday'],
      ['2020-04-10', 'Good Friday'],
      ['2020-05-25', 'Memorial Day'],
      ['2020-07-03', 'Independence Day'],
      ['2020-09-07', 'Labor Day'],
      ['2020-11-26', 'Thanksgiving Day'],
      ['2020-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2020-11-27', 'Day after Thanksgiving'],
      ['2020-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2021,
    closures: [
      ['2021-01-01', 'New Year\'s Day'],
      ['2021-01-18', 'Martin Luther King Jr. Day'],
      ['2021-02-15', 'Washington\'s Birthday'],
      ['2021-04-02', 'Good Friday'],
      ['2021-05-31', 'Memorial Day'],
      ['2021-07-05', 'Independence Day'],
      ['2021-09-06', 'Labor Day'],
      ['2021-11-25', 'Thanksgiving Day'],
      ['2021-12-24', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2021-11-26', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2022,
    closures: [
      ['2022-01-17', 'Martin Luther King Jr. Day'],
      ['2022-02-21', 'Washington\'s Birthday'],
      ['2022-04-15', 'Good Friday'],
      ['2022-05-30', 'Memorial Day'],
      ['2022-06-20', 'Juneteenth National Independence Day'],
      ['2022-07-04', 'Independence Day'],
      ['2022-09-05', 'Labor Day'],
      ['2022-11-24', 'Thanksgiving Day'],
      ['2022-12-26', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2022-11-25', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2023,
    closures: [
      ['2023-01-02', 'New Year\'s Day'],
      ['2023-01-16', 'Martin Luther King Jr. Day'],
      ['2023-02-20', 'Washington\'s Birthday'],
      ['2023-04-07', 'Good Friday'],
      ['2023-05-29', 'Memorial Day'],
      ['2023-06-19', 'Juneteenth National Independence Day'],
      ['2023-07-04', 'Independence Day'],
      ['2023-09-04', 'Labor Day'],
      ['2023-11-23', 'Thanksgiving Day'],
      ['2023-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2023-07-03', 'Day before Independence Day'],
      ['2023-11-24', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2024,
    closures: [
      ['2024-01-01', 'New Year\'s Day'],
      ['2024-01-15', 'Martin Luther King Jr. Day'],
      ['2024-02-19', 'Washington\'s Birthday'],
      ['2024-03-29', 'Good Friday'],
      ['2024-05-27', 'Memorial Day'],
      ['2024-06-19', 'Juneteenth National Independence Day'],
      ['2024-07-04', 'Independence Day'],
      ['2024-09-02', 'Labor Day'],
      ['2024-11-28', 'Thanksgiving Day'],
      ['2024-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2024-07-03', 'Day before Independence Day'],
      ['2024-11-29', 'Day after Thanksgiving'],
      ['2024-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2025,
    closures: [
      ['2025-01-01', 'New Year\'s Day'],
      ['2025-01-20', 'Martin Luther King Jr. Day'],
      ['2025-02-17', 'Washington\'s Birthday'],
      ['2025-04-18', 'Good Friday'],
      ['2025-05-26', 'Memorial Day'],
      ['2025-06-19', 'Juneteenth National Independence Day'],
      ['2025-07-04', 'Independence Day'],
      ['2025-09-01', 'Labor Day'],
      ['2025-11-27', 'Thanksgiving Day'],
      ['2025-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2025-07-03', 'Day before Independence Day'],
      ['2025-11-28', 'Day after Thanksgiving'],
      ['2025-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2026,
    closures: [
      ['2026-01-01', 'New Year\'s Day'],
      ['2026-01-19', 'Martin Luther King Jr. Day'],
      ['2026-02-16', 'Washington\'s Birthday'],
      ['2026-04-03', 'Good Friday'],
      ['2026-05-25', 'Memorial Day'],
      ['2026-06-19', 'Juneteenth National Independence Day'],
      ['2026-07-03', 'Independence Day'],
      ['2026-09-07', 'Labor Day'],
      ['2026-11-26', 'Thanksgiving Day'],
      ['2026-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2026-11-27', 'Day after Thanksgiving'],
      ['2026-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2027,
    closures: [
      ['2027-01-01', 'New Year\'s Day'],
      ['2027-01-18', 'Martin Luther King Jr. Day'],
      ['2027-02-15', 'Washington\'s Birthday'],
      ['2027-03-26', 'Good Friday'],
      ['2027-05-31', 'Memorial Day'],
      ['2027-06-18', 'Juneteenth National Independence Day'],
      ['2027-07-05', 'Independence Day'],
      ['2027-09-06', 'Labor Day'],
      ['2027-11-25', 'Thanksgiving Day'],
      ['2027-12-24', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2027-11-26', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2028,
    closures: [
      ['2028-01-17', 'Martin Luther King Jr. Day'],
      ['2028-02-21', 'Washington\'s Birthday'],
      ['2028-04-14', 'Good Friday'],
      ['2028-05-29', 'Memorial Day'],
      ['2028-06-19', 'Juneteenth National Independence Day'],
      ['2028-07-04', 'Independence Day'],
      ['2028-09-04', 'Labor Day'],
      ['2028-11-23', 'Thanksgiving Day'],
      ['2028-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2028-07-03', 'Day before Independence Day'],
      ['2028-11-24', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2029,
    closures: [
      ['2029-01-01', 'New Year\'s Day'],
      ['2029-01-15', 'Martin Luther King Jr. Day'],
      ['2029-02-19', 'Washington\'s Birthday'],
      ['2029-03-30', 'Good Friday'],
      ['2029-05-28', 'Memorial Day'],
      ['2029-06-19', 'Juneteenth National Independence Day'],
      ['2029-07-04', 'Independence Day'],
      ['2029-09-03', 'Labor Day'],
      ['2029-11-22', 'Thanksgiving Day'],
      ['2029-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2029-07-03', 'Day before Independence Day'],
      ['2029-11-23', 'Day after Thanksgiving'],
      ['2029-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2030,
    closures: [
      ['2030-01-01', 'New Year\'s Day'],
      ['2030-01-21', 'Martin Luther King Jr. Day'],
      ['2030-02-18', 'Washington\'s Birthday'],
      ['2030-04-19', 'Good Friday'],
      ['2030-05-27', 'Memorial Day'],
      ['2030-06-19', 'Juneteenth National Independence Day'],
      ['2030-07-04', 'Independence Day'],
      ['2030-09-02', 'Labor Day'],
      ['2030-11-28', 'Thanksgiving Day'],
      ['2030-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2030-07-03', 'Day before Independence Day'],
      ['2030-11-29', 'Day after Thanksgiving'],
      ['2030-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2031,
    closures: [
      ['2031-01-01', 'New Year\'s Day'],
      ['2031-01-20', 'Martin Luther King Jr. Day'],
      ['2031-02-17', 'Washington\'s Birthday'],
      ['2031-04-11', 'Good Friday'],
      ['2031-05-26', 'Memorial Day'],
      ['2031-06-19', 'Juneteenth National Independence Day'],
      ['2031-07-04', 'Independence Day'],
      ['2031-09-01', 'Labor Day'],
      ['2031-11-27', 'Thanksgiving Day'],
      ['2031-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2031-07-03', 'Day before Independence Day'],
      ['2031-11-28', 'Day after Thanksgiving'],
      ['2031-12-24', 'Christmas Eve'],
    ],
  },
  {
    year: 2032,
    closures: [
      ['2032-01-01', 'New Year\'s Day'],
      ['2032-01-19', 'Martin Luther King Jr. Day'],
      ['2032-02-16', 'Washington\'s Birthday'],
      ['2032-03-26', 'Good Friday'],
      ['2032-05-31', 'Memorial Day'],
      ['2032-06-18', 'Juneteenth National Independence Day'],
      ['2032-07-05', 'Independence Day'],
      ['2032-09-06', 'Labor Day'],
      ['2032-11-25', 'Thanksgiving Day'],
      ['2032-12-24', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2032-11-26', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2033,
    closures: [
      ['2033-01-17', 'Martin Luther King Jr. Day'],
      ['2033-02-21', 'Washington\'s Birthday'],
      ['2033-04-15', 'Good Friday'],
      ['2033-05-30', 'Memorial Day'],
      ['2033-06-20', 'Juneteenth National Independence Day'],
      ['2033-07-04', 'Independence Day'],
      ['2033-09-05', 'Labor Day'],
      ['2033-11-24', 'Thanksgiving Day'],
      ['2033-12-26', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2033-11-25', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2034,
    closures: [
      ['2034-01-02', 'New Year\'s Day'],
      ['2034-01-16', 'Martin Luther King Jr. Day'],
      ['2034-02-20', 'Washington\'s Birthday'],
      ['2034-04-07', 'Good Friday'],
      ['2034-05-29', 'Memorial Day'],
      ['2034-06-19', 'Juneteenth National Independence Day'],
      ['2034-07-04', 'Independence Day'],
      ['2034-09-04', 'Labor Day'],
      ['2034-11-23', 'Thanksgiving Day'],
      ['2034-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2034-07-03', 'Day before Independence Day'],
      ['2034-11-24', 'Day after Thanksgiving'],
    ],
  },
  {
    year: 2035,
    closures: [
      ['2035-01-01', 'New Year\'s Day'],
      ['2035-01-15', 'Martin Luther King Jr. Day'],
      ['2035-02-19', 'Washington\'s Birthday'],
      ['2035-03-23', 'Good Friday'],
      ['2035-05-28', 'Memorial Day'],
      ['2035-06-19', 'Juneteenth National Independence Day'],
      ['2035-07-04', 'Independence Day'],
      ['2035-09-03', 'Labor Day'],
      ['2035-11-22', 'Thanksgiving Day'],
      ['2035-12-25', 'Christmas Day'],
    ],
    earlyCloses: [
      ['2035-07-03', 'Day before Independence Day'],
      ['2035-11-23', 'Day after Thanksgiving'],
      ['2035-12-24', 'Christmas Eve'],
    ],
  },
];
